plugins:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle:
    - table
    - key
  EnforcedHashRocketStyle:
    - table
    - key

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 145

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "test/**/*"
    - "lib/scalingo_staging_sync/support/parallel_processor.rb"
    - "lib/scalingo_staging_sync/support/environment_validator.rb"
    - "lib/scalingo_staging_sync/services/database_anonymizer_service.rb"
    - "lib/scalingo_staging_sync/database/anonymization_audit.rb"
    - "lib/scalingo_staging_sync/database/anonymization_verifier.rb"
    - "lib/scalingo_staging_sync/database/pii_scanner.rb"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Rakefile"
    - "test/**/*"

Metrics/ClassLength:
  Max: 120
  Exclude:
    - "test/**/*"
    - "lib/scalingo_staging_sync/services/database_anonymizer_service.rb"

Metrics/MethodLength:
  Max: 21
  Exclude:
    - "test/**/*"
    - "lib/scalingo_staging_sync/database/transaction_helpers.rb"
    - "lib/scalingo_staging_sync/database/table_anonymizer.rb"
    - "lib/scalingo_staging_sync/services/database_anonymizer_service.rb"
    - "lib/scalingo_staging_sync/support/environment_validator.rb"
    - "lib/scalingo_staging_sync/database/anonymization_audit.rb"
    - "lib/scalingo_staging_sync/database/anonymization_verifier.rb"
    - "lib/scalingo_staging_sync/database/pii_scanner.rb"

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - "test/**/*"
    - "lib/scalingo_staging_sync/support/parallel_processor.rb"
    - "lib/scalingo_staging_sync/support/environment_validator.rb"
    - "lib/scalingo_staging_sync/database/anonymization_audit.rb"
    - "lib/scalingo_staging_sync/database/anonymization_verifier.rb"
    - "lib/scalingo_staging_sync/database/pii_scanner.rb"
    - "lib/scalingo_staging_sync/database/anonymization_queries.rb"

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - "test/**/*"
    - "lib/scalingo_staging_sync/services/database_anonymizer_service.rb"

Metrics/ParameterLists:
  Max: 6

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/scalingo-staging-sync.rb

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - "test/**/*"
    - "lib/scalingo_staging_sync/services/database_anonymizer_service.rb"
    - "lib/scalingo_staging_sync/database/anonymization_audit.rb"
    - "lib/scalingo_staging_sync/database/anonymization_verifier.rb"
    - "lib/scalingo_staging_sync/database/pii_scanner.rb"

Style/FetchEnvVar:
  Exclude:
    - test/test_helper.rb

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true

Style/SafeNavigationChainLength:
  Exclude:
    - "lib/scalingo_staging_sync/database/anonymization_audit.rb"

Lint/UselessConstantScoping:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 5
